Updated rules
Henry055/RokucraftWiki pull request #5
Opened 2021-04-20 21:18 UTC by Aikovdp

Uwu! I've updated all the rules (including roleplay) to their final version. I've cleaned up some minor things like <br> tags and questionable spacing in the files too, and rephrased something here and there.

Wiki finished?

2021-04-21 20:07 UTC, Henry055 requested changes
I've also noticed the numbers in the code aren't consistent throughout the list (e.g. two rule 10's) Although this isn't noticed in the markdown preview / on the wiki, it's kind of ugly and confusing for others who might read the code (I assume the numbering was a mistake as well)

2021-04-21 20:07 UTC, Henry055 commented on docs/roleplay/roleplay-rules.md
> +Use the roleplay chats ([`/ch rp` in-game](/gameplay/chat-system)) when roleplaying to avoid confusion.
Personally, I'm not too big of a fan of the way links look inside the code lines. It might just be my personal preference so I am interested on your views on how it looks but maybe you could try moving the hyperlink to 'roleplay chats' or possibly use a foot note instead?

2021-04-21 20:10 UTC, Henry055 commented on docs/server-related/rules.md
> +## Houses & Shops
This is possibly a comment more about our rule layout but maybe using the word 'Housing' would be a more appropriate title? I'm looking at the ToC locally and 'Houses & Shops' doesn't feel fitting alongside the other section headings

2021-04-21 20:12 UTC, Henry055 commented on docs/roleplay/roleplay-rules.md
> +[^3]: You can find each nation's Discord server through the main [Rokucraft Discord server](https://discord.gg/7WNFu3v). The invite links are pinned in the `#roleplay-announcements` channel.
Similar to my comment about the link within the code block; I'm also not sure whether I like the use of code text inside a footnote, it stands out (as I assume you intended) but I'm not sure if it's a bit *too* much? Personally I'm not a huge fan of how it looks but what do you think?

2021-04-21 20:15 UTC, Aikovdp commented on docs/roleplay/roleplay-rules.md
> +Use the roleplay chats ([`/ch rp` in-game](/gameplay/chat-system)) when roleplaying to avoid confusion.
We have roleplay chats on other platforms too. Only the in-game example links to the explanation on in-game chats

2021-04-21 20:16 UTC, Aikovdp commented on docs/server-related/rules.md
> +## Houses & Shops
Housing and shops is strange too tho, bc then it feels like it should be "housing and shopping" but that's wrong ofc lmao

2021-04-21 20:24 UTC, Henry055 commented on docs/roleplay/roleplay-rules.md
> +Use the roleplay chats ([`/ch rp` in-game](/gameplay/chat-system)) when roleplaying to avoid confusion.
```
**Use roleplay chats**[^1]  
Use the roleplay chats (`/ch rp` in-game) when roleplaying to avoid confusion.

[^1]: If you aren't sure how our in-game chat system works you can read an in-depth explanation on our [Chat System Tutorial](/gameplay/chat-system) page.
```

This is a rough example I made of what it could look like as a footnote instead of in the code block and I personally prefer it, I just find links in code blocks super ugly

2021-04-21 20:25 UTC, Henry055 commented on docs/server-related/rules.md
> +## Houses & Shops
Yeah I didn't think of that too much, we can just leave it as 'Houses & Shops' then

2021-04-21 22:29 UTC, Aikovdp commented on docs/roleplay/roleplay-rules.md
> +[^3]: You can find each nation's Discord server through the main [Rokucraft Discord server](https://discord.gg/7WNFu3v). The invite links are pinned in the `#roleplay-announcements` channel.
I kinda like it better as code, it looks a bit out of place if you're just using regular text

2021-04-21 22:39 UTC, Aikovdp commented on docs/roleplay/roleplay-rules.md
> +Use the roleplay chats ([`/ch rp` in-game](/gameplay/chat-system)) when roleplaying to avoid confusion.
Should be fixed now

2021-04-22 06:28 UTC, merged

2021-04-22 06:29 UTC, Henry055 commented
thank yew